/*QUERY*/
export const SET_QUERY = "SET_QUERY";

/*FAVORITES*/
export const ADD_IMAGE_TO_FAVORITES = 'ADD_IMAGE_TO_FAVORITES';
export const REMOVE_IMAGE_FROM_FAVORITES = "REMOVE_IMAGE_FROM_FAVORITES";

/*SEARCH HISTORY*/
export const ADD_TO_SEARCH_HISTORY = "ADD_TO_SEARCH_HISTORY";
export const CLEAR_SEARCH_HISTORY = "CLEAR_SEARCH_HISTORY";